spring:
  application:
    name: room-reservation-service
  datasource:
    url: jdbc:h2:mem:reservations;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
    static-path-pattern: /static/**
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  kafka:
    listener:
      auto-startup: false
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reservation-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092

app:
  cancellation:
    days-before: 2
  credit-card:
    payment-service-url: http://wiremock:8080/host/credit-card-payment-api/payment-status

server:
  error:
      include-message: always
      include-stacktrace: always